### ISSUE TITLE
Discord bot replies URLs with periods

### ISSUE THREAD

**Issue by 0xkeenz** [pandodao/PAL9000#6]
The URL that the bot replies to always has a ` 。`, causing the URL to fail to open normally.

The following is an example image：

![image](https://github.com/pandodao/PAL9000/assets/108882370/9b1cc84d-246e-4aeb-919f-daafa37c8a68)
![image](https://github.com/pandodao/PAL9000/assets/108882370/28301ddd-e077-4954-9af0-b42e1cf63a69)

**Comment by xwjdsh** [comment]
This is annoying. Let me try, maybe I can add some formatting code to fix this.

**Comment by xwjdsh** [comment]
We added the option to format the links in the response, you can config like the following,
```
general:
  options:
    format_links: true
```
