### ISSUE TITLE
Discord can only trigger bots via @

### ISSUE THREAD

**Issue by 0xkeenz** [pandodao/PAL9000#7]
Discord can only trigger the bot through the @ method. If you ask a question directly in the channel or use "Reply" to ask a question, the bot will not respond normally

**Comment by xwjdsh** [comment]
Thanks for the feedback. I've added support for replying to messages in #8 .

> ask a question directly in the channel

I'm a bit confused about this requirement. Generally, there are many users in a channel, and if the bot ignores the @ limit when replying to messages, it may disrupt the normal messages between users.

**Comment by 0xkeenz** [comment]
Sorry, this is just an idea, it might be interesting if bots communicate directly with humans in a chat on a specific channel...

**Comment by xwjdsh** [comment]
I apologize for closing this without explanation, I forgot :-). We added support for triggering a request by replying to a message, but it's not common to ask questions directly in the channel, and we've decided not to support it for now.
